### PR TITLE
Select multi dependances

### PR DESCRIPTION
**Pull request by fluchier**

### CODE REVIEW

**Comment by harkirat10** [comment]
-- Please reply above this line --


Hi Razuna/razuna,

We received your request for help! While we will get to your email as
soon as possible here are a couple of important notes for you:

	* If you haven't done so, please take a look at our Documentation.
Many topics are already covered http://wiki.razuna.com [1]
	* Another point of support is our public forum
at http://forums.razuna.com [2]

PLEASE NOTE THAT WE WILL ONLY PROVIDE DIRECT SUPPORT FOR CUSTOMERS OF
OUR HOSTED EDITION OR IF YOU HAVE A VALID SUPPORT SUBSCRIPTION.

Thanks!

Links:
------
[1] http://wiki.razuna.com
[2] http://forums.razuna.com

**Comment by fluchier** [comment]
Hello,

Sorry for this request, i'm trying to cancel it but you can cancel it yourself if you want.

Regards.
--
Florian Luchier
J2S, Just Simple Solutions
Les logiciels du succ�s de votre communication


03 20 17 63 00
http://www.j2s.net




Le 13 ao�t 2015 � 16:10, harkirat10 <notifications@github.com> a �crit :

> -- Please reply above this line --
> 
> 
> Hi Razuna/razuna,
> 
> We received your request for help! While we will get to your email as
> soon as possible here are a couple of important notes for you:
> 
> * If you haven't done so, please take a look at our Documentation.
> Many topics are already covered http://wiki.razuna.com [1]
> * Another point of support is our public forum
> at http://forums.razuna.com [2]
> 
> PLEASE NOTE THAT WE WILL ONLY PROVIDE DIRECT SUPPORT FOR CUSTOMERS OF
> OUR HOSTED EDITION OR IF YOU HAVE A VALID SUPPORT SUBSCRIPTION.
> 
> Thanks!
> 
> Links:
> ------
> [1] http://wiki.razuna.com
> [2] http://forums.razuna.com
> 
> 
> 
>

**Comment by harkirat10** [comment]
-- Please reply above this line --


Hi Razuna/razuna,

We received your request for help! While we will get to your email as
soon as possible here are a couple of important notes for you:

	* If you haven't done so, please take a look at our Documentation.
Many topics are already covered http://wiki.razuna.com [1]
	* Another point of support is our public forum
at http://forums.razuna.com [2]

PLEASE NOTE THAT WE WILL ONLY PROVIDE DIRECT SUPPORT FOR CUSTOMERS OF
OUR HOSTED EDITION OR IF YOU HAVE A VALID SUPPORT SUBSCRIPTION.

Thanks!

Links:
------
[1] http://wiki.razuna.com
[2] http://forums.razuna.com

**Comment by thenitai** [comment]
Hi Florian,

It's already closed. If you want to open a new one please re-submit a pull request. 

Thank you and I hope you are doing fine.

Cheers,
Nitai

**Comment by harkirat10** [comment]
-- Please reply above this line --


Hi Razuna/razuna,

We received your request for help! While we will get to your email as
soon as possible here are a couple of important notes for you:

	* If you haven't done so, please take a look at our Documentation.
Many topics are already covered http://wiki.razuna.com [1]
	* Another point of support is our public forum
at http://forums.razuna.com [2]

PLEASE NOTE THAT WE WILL ONLY PROVIDE DIRECT SUPPORT FOR CUSTOMERS OF
OUR HOSTED EDITION OR IF YOU HAVE A VALID SUPPORT SUBSCRIPTION.

Thanks!

Links:
------
[1] http://wiki.razuna.com
[2] http://forums.razuna.com

**Pull request closed without merging**
